.TH bitlespeak "1" "20 July 2010"

.SH NAME
bitlespeak \- GNOME text to speech frontend

.SH SYNOPSIS
\fBbitlespeak

.SH DESCRIPTION
\fBbitlespeak\fR launchs gtk speech frontend

.SH OPTIONS
This is a placeholder currently there are no command line options
.TP



.SH AUTHOR
\fBbitlespeak\fR was written by Matt Arnold <mattarnold5@gmail.com>.

